### ISSUE TITLE
Parsing failure when "r" type of variable (measType) has no value (measValue) 

### ISSUE THREAD

**Issue by jsanz01** [bodastage/boda-measdatacollectionparser#10]
Hi,
I have realized that in this latest parser version, when I introduce a XML file that declares (measType tag) for example 5 available counters names but in one of the included devices, only 3 of those counters reports values, then the parsing process is stopped because source code tries to find (one to one) declared variable with reported counter value.

XML Schema supports the values as optional for a given device. So it is a valid situation.

So, in my opinion, the number of elements in the measTypesList array could be equal but also greater than the number of elements in the measResultsList array.
Let me put an example: 13 declared counters but for this network element only 8 values are received. Parser reports en error ("key not found: 6") and execution is interrupted because variable number 6 is not reporting any counter value. 

>
		<measData>
			<managedElement localDn="ManagedElement=Network/Switch"/>
			<measInfo>
			<granPeriod duration="PT900S" endTime="2019-07-23T15:35:00+00:00"/>
				<measType p="1">ifHCInOctets_ifHCInOctets</measType>
				<measType p="2">ifHCInUcastPkts_ifHCInUcastPkts</measType>
				<measType p="3">ifHCOutOctets_ifHCOutOctets</measType>
				<measType p="4">ifHCOutUcastPkts_ifHCOutUcastPkts</measType>
				<measType p="5">ifInErrors_ifInErrors</measType>
				<measType p="6">ifInOctets_ifInOctets</measType>
				<measType p="7">ifInUcastPackets_ifInUcastPackets</measType>
				<measType p="8">ifOperStatusPolled_ifOperStatusPolled</measType>
				<measType p="9">ifOperStatus_ifOperStatus</measType>
				<measType p="10">ifOutErrors_ifOutErrors</measType>
				<measType p="11">ifOutOctets_ifOutOctets</measType>
				<measType p="12">ifOutUcastPackets_ifOutUcastPackets</measType>
				<measType p="13">sysUpTime_sysUpTime</measType>
				<measValue measObjLdn="UPTB-ES00M-NO-0001/os/interfaces/iface29">
					<r p="4">206483017.0</r>
					<r p="5">0.0</r>
					<r p="3">43876537023.0</r>
					<r p="9">1.0</r>
					<r p="10">0.0</r>
					<r p="1">181234731528.0</r>
					<r p="8">1.0</r>
					<r p="2">436283885.0</r>
				</measValue>
			</measInfo>
		</measData>

**Comment by erssebaggala** [comment]
@jsanz01 i had assumed all results are present for all listed measurement types.  This is a simple fix though; let me work on it. Thanks for reporting this.

**Comment by erssebaggala** [comment]
Resolved by PR #11
